export const adjectives = [
    "Adventurous", "Brave", "Calm", "Delightful", "Eager", "Faithful", "Gentle",
    "Happy", "Inventive", "Jolly", "Kind", "Lively", "Merry", "Nice", "Obedient",
    "Proud", "Quiet", "Relieved", "Silly", "Thankful", "Victorious", "Witty",
    "Zealous", "Angry", "Bewildered", "Clumsy", "Defeated", "Embarrassed",
    "Fierce", "Grumpy", "Helpless", "Itchy", "Jealous", "Lazy", "Mysterious",
    "Nervous", "Obnoxious", "Panicky", "Repulsive", "Scary", "Thoughtless",
    "Uptight", "Worried", "Agreeable", "Amiable", "Arrogant", "Audacious",
    "Benevolent", "Brilliant", "Candid", "Charming", "Cheerful", "Compassionate",
    "Confident", "Courageous", "Creative", "Curious", "Daring", "Determined",
    "Diligent", "Eccentric", "Elegant", "Eloquent", "Enthusiastic", "Exuberant",
    "Fancy", "Fearless", "Festive", "Friendly", "Funny", "Generous", "Gifted",
    "Glamorous", "Gleeful", "Glorious", "Graceful", "Gregarious", "Honest",
    "Humble", "Humorous", "Imaginative", "Independent", "Innocent", "Intelligent",
    "Joyful", "Jubilant", "Keen", "Loyal", "Magnificent", "Majestic",
    "Mischievous", "Modest", "Optimistic", "Passionate", "Peaceful", "Playful", 
    "Polite", "Powerful", "Precious", "Protective", "Radiant", "Reckless", 
    "Reliable", "Resourceful", "Romantic", "Rough", "Rude", "Sarcastic", 
    "Sassy", "Sensible", "Serious", "Sharp", "Shy", "Silly", "Sincere", 
    "Sleepy", "Slow", "Smooth", "Sneaky", "Sparkling", "Splendid", "Strange", 
    "Strong", "Stunning", "Sweet", "Talented", "Tame", "Tender", "Thoughtful", 
    "Timid", "Tough", "Tricky", "Troubled", "Trustworthy", "Unique", "Vivacious",
    "Vulnerable", "Warm", "Wild", "Wise", "Zany"
  ];
  
  export const nouns = [
    "Tiger", "Eagle", "Shark", "Lion", "Panther", "Wolf", "Bear", "Fox", "Hawk",
    "Falcon", "Leopard", "Jaguar", "Cheetah", "Cougar", "Lynx", "Bobcat",
    "Ocelot", "Puma", "Hyena", "Jackal", "Coyote", "Dingo", "Otter", "Beaver",
    "Raccoon", "Skunk", "Badger", "Weasel", "Mink", "Ferret", "Squirrel",
    "Chipmunk", "Hedgehog", "Porcupine", "Armadillo", "Sloth", "Anteater",
    "Aardvark", "Platypus", "Kangaroo", "Wallaby", "Koala", "Possum", "Wombat",
    "Tasmanian Devil", "Mongoose", "Meerkat", "Lemur", "Monkey", "Gorilla",
    "Chimpanzee", "Orangutan", "Baboon", "Gibbon", "Macaque", "Mandrill",
    "Tamarin", "Capuchin", "Saki", "Howler Monkey", "Spider Monkey",
    "Squirrel Monkey", "Marmoset", "Tarsier", "Aye-aye", "Loris", "Galago",
    "Bushbaby", "Pangolin", "Elephant", "Rhinoceros", "Hippopotamus", "Giraffe",
    "Zebra", "Horse", "Donkey", "Mule", "Camel", "Llama", "Alpaca", "Vicuna",
    "Guanaco", "Buffalo", "Bison", "Yak", "Cow", "Bull", "Ox", "Goat",
    "Albatross", "Antelope", "Bat", "Bluebird", "Butterfly", "Caterpillar",
    "Cobra", "Crane", "Crocodile", "Crow", "Deer", "Dog", "Dolphin", "Dove",
    "Dragonfly", "Duck", "Eel", "Flamingo", "Fly", "Frog", "Gazelle", "Gecko",
    "Goose", "Gopher", "Grasshopper", "Hare", "Heron", "Hornet", "Horsefly",
    "Hummingbird", "Iguana", "Jellyfish", "Ladybug", "Lobster", "Manatee",
    "Mole", "Moose", "Mosquito", "Moth", "Mouse", "Nightingale", "Octopus",
    "Ostrich", "Owl", "Oyster", "Parrot", "Peacock", "Penguin", "Pig", "Pigeon",
    "Pony", "Porpoise", "Python", "Rabbit", "Rat", "Raven", "Reindeer", 
    "Salamander", "Salmon", "Scorpion", "Seagull", "Seahorse", "Seal", "Sheep", 
    "Shrew", "Skink", "Snake", "Sparrow", "Spider", "Squid", "Starfish", "Stork",
    "Swan", "Termite", "Toad", "Tortoise", "Turkey", "Turtle", "Vulture", "Walrus",
    "Wasp", "Whale", "Wildcat", "Wolf", "Wolverine", "Woodpecker", "Worm" 
  ];